### PR TITLE
Persist rerolls

### LINKED ISSUE #125: rerolling character should provide some benefits
your lockers should not be wiped (or they should be copied), you should keep half of the exp of the old character, and all skill values should be moved to the paid skills for the new character at a rate of 1:1

### PR DESCRIPTION
**Pull request by sarimash**
### All Submissions

* [x] Have you followed the guidelines in our Contributing document?
* [x] Can you post a screenshot of your changes (if applicable)?

image
image

### New Feature Submissions

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally prior to submission?

### Changes to Core Features

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
 Closes #125

### CODE REVIEW

**Comment by sarimash** [comment]
Adding three comments for separate reply chains...
Started working on this and wanted to get some feedback on the approach; I guess it's bad that it's decoupling the starting EXP, and the 1000 is hardcoded in both this function and the CharacterInitializer, but I was trying to create a variable that would be safe to overwrite in the "rerolling" block.

**Comment by sarimash** [comment]
I tried to get the locker information from LockerHelper but it looks like LockerHelper is more for displaying them than maintaining the contents; would it be better to add functionality to LockerHelper for this cloning instead of just caching and restoring?

**Comment by sarimash** [comment]
I haven't begun work on converting skills to paid training yet.

**Comment by seiyria** [comment]
re: 1000

this is fine for now, if desired we can track adding it to the game settings (in content/core/settings.yml).

re: lockerhelper

adding helpers seems fine to me if desired

and cool, when the training is done I'll check it out. ideally, it'll be: `player.paidSkills = Object.assign({}, oldplayer.skills)` or something.

**Comment by seiyria** [comment]
whew I have wanted to get this in forever. I got it in, but the work was done here. thanks!

**Pull request closed without merging**
